### PR TITLE
Added Encoding type

### LINKED ISSUE #2: Error en el encoding al leer un valor del fichero properties
Al obtener del fichero `application.properties` el valor de la propiedad `app.description`, debido al encoding del fichero el texto no se muestra correctamente.

En la clase `AppConfig` se puede ver este problema en la propiedad `appDescription`
image

### PR DESCRIPTION
**Pull request by chinmaym07**
fixes: #2

### CODE REVIEW

**Comment by nmarulo** [comment]
image

The characters are still displayed incorrectly. Please, you can check it.
Before making any further changes, please update your master branch.

**Comment by nmarulo** [comment]
@chinmaym07  please confirm if you are still interested in working on this assignment, thank you.

**Comment by chinmaym07** [comment]
Yes @nmarulo  I am working on this pr.

**Comment by chinmaym07** [comment]
Hi @nmarulo I tried most of the approaches. but couldn't get this resolved. can you please help ?

**Comment by nmarulo** [comment]
@chinmaym07 

The problem here, is that the `pom.xml` file is encoded in `utf-8` and the properties files in `iso-8859-1`.

I can think of some solutions (if you have already tried them tell me what solutions you have tried):

One solution (possibly the most correct one) is to change the properties files to `yaml` files.

Another solution could be: in the AppProperties class, implement the getter methods of the conflicting properties and get the bytes in the correct encoding and return a new String (although this would be a temporary solution).
EJ: `new String(appProperties.getAppDescription().getBytes(StandardCharsets.ISO_8859_1));`

At the moment I can only think of this, I would have to investigate further.

**Comment by nmarulo** [comment]
If you find it complicated, don't worry, I'll look into it later.

**Comment by chinmaym07** [comment]
You are right @nmarulo . I tried solution like except the yaml one.
1. Forcing encoding type
2. Creating Custom Resource builder.
3. EJ which you mentioned but with incorrect encoding type.

Should I update the PR with yaml file change or the temporary solution ?

**Comment by nmarulo** [comment]
@chinmaym07 
The solutions I gave were because I remember that I read something at the time, but I didn't investigate it thoroughly, so I don't know if they are the correct solutions.

Implement the one that works for you.

**Pull request closed without merging**
