### PR TITLE
Github Actions configured for creating a test report & uploading it

### LINKED ISSUE #3: Configurar Github Action
Crear la carpeta `.github/workflows/` y el fichero `maven.yml` con la siguiente información:

```yml
name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Compile with Maven
      run: mvn -B compile --file pom.xml
      
    - name: Test
      run: mvn -B test --file pom.xml
```

Además, agregar la configuración de deepsource para que se suba el reporte de cobertura de los test.

- Agregar la dependencia para generar el reporte: https://deepsource.io/docs/analyzer/test-coverage/#java
- Agregar la configuración de deepsource: https://deepsource.io/docs/analyzer/test-coverage/#with-github-actions-3
   - La variable de entorno `DEEPSOURCE_DSN` ya esta creada.

### PR DESCRIPTION
**Pull request by chinmaym07**
fixes: #3

### CODE REVIEW

**Comment by nmarulo** [comment]
Please set the latest version of Jacoco, the current one does not work in java 17, which causes it not to compile the project.


Also correct the report path (the value after `--value-file`), to `./target/site/jacoco/jacoco.xml` as this is the file it generates and it is the same name of the file indicated in the deepsource docs.

**Comment by nmarulo** [comment]
please could you also check why you have so many modified lines in the `pom.xml` file, if you have only added 20 lines, it should not be like that:

image

**Comment by chinmaym07** [comment]
Updated @nmarulo .
Please check.

**Comment by nmarulo** [comment]
Great, thank you very much.
It looks good

**Pull request merged**
